"""sg

Revision ID: 06505539c2e6
Revises: 95f7cde3f6e1
Create Date: 2025-05-16 16:38:43.201507

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "06505539c2e6"
down_revision: Union[str, None] = "95f7cde3f6e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
