"""sg

Revision ID: 2f44cc7d22ac
Revises: fc02373447ae
Create Date: 2025-05-21 14:48:35.152553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "2f44cc7d22ac"
down_revision: Union[str, None] = "fc02373447ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "navigation",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("navigation", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "navigation",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("navigation", "title")
    # ### end Alembic commands ###
