"""sg

Revision ID: 91e598afa5f7
Revises: cf640bf68538
Create Date: 2025-05-16 14:12:08.071622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "91e598afa5f7"
down_revision: Union[str, None] = "cf640bf68538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("meta_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "meta_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("meta_keywords", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("canonical_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "robots_directives", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("og_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("structured_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_markdown", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_field", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    # ### end Alembic commands ###
