"""sg

Revision ID: af949932c723
Revises: fea99af9badf
Create Date: 2025-05-20 10:03:23.011772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af949932c723"
down_revision: Union[str, None] = "fea99af9badf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page", sa.Column("unpublished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "page",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.add_column(
        "page", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_page_is_deleted"), "page", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_page_slug"), "page", ["slug"], unique=True)
    op.add_column(
        "post", sa.Column("unpublished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "post",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.add_column(
        "post", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_post_is_deleted"), "post", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_post_slug"), "post", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_slug"), table_name="post")
    op.drop_index(op.f("ix_post_is_deleted"), table_name="post")
    op.drop_column("post", "deleted_at")
    op.drop_column("post", "is_deleted")
    op.drop_column("post", "unpublished_at")
    op.drop_index(op.f("ix_page_slug"), table_name="page")
    op.drop_index(op.f("ix_page_is_deleted"), table_name="page")
    op.drop_column("page", "deleted_at")
    op.drop_column("page", "is_deleted")
    op.drop_column("page", "unpublished_at")
    # ### end Alembic commands ###
