"""sg

Revision ID: cf640bf68538
Revises: 24ddca580d3e
Create Date: 2025-05-16 13:13:06.628371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "cf640bf68538"
down_revision: Union[str, None] = "24ddca580d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "navigation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "page",
        sa.Column("meta_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "meta_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("meta_keywords", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("canonical_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "robots_directives", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("og_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("og_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("structured_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_markdown", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body_field", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "navigationitem",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("page_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("navigation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["navigation_id"],
            ["navigation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["navigationitem.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("navigationitem")
    op.drop_table("page")
    op.drop_table("navigation")
    # ### end Alembic commands ###
