"""sg

Revision ID: e0c0a89a68c4
Revises: b20ef27dae64
Create Date: 2025-05-17 12:20:25.389403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0c0a89a68c4"
down_revision: Union[str, None] = "b20ef27dae64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("upload", sa.Column("public", sa.Boolean(), nullable=False))
    op.drop_column("upload", "is_public")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload",
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("upload", "public")
    # ### end Alembic commands ###
