"""sg

Revision ID: fb5c873dd820
Revises: e0c0a89a68c4
Create Date: 2025-05-19 17:40:46.441034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb5c873dd820"
down_revision: Union[str, None] = "e0c0a89a68c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.add_column(
        "user", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_staff", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.alter_column("user", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_staff", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "is_deleted")
    # ### end Alembic commands ###
